all: diskinfo disklist diskget diskput

diskinfo:
	gcc -o diskinfo diskinfo.c

disklist:
	gcc -o disklist disklist.c
	
diskget:
	gcc -o diskget diskget.c
	
diskput:
	gcc -o diskput diskput.c
	
clean:
	rm -f diskinfo disklist diskget diskput
